server:
  servlet:
    context-path: /api
  port: 8081
spring:
  profiles:
    active:
      - local
    group:
      local:
        - local-db
        - local-oauth2
        - local-common
        - local-service
      dev:
        - dev-db
        - dev-oauth2
        - dev-common
        - dev-service
      prod:
        - prod-db
        - prod-oauth2
        - prod-common
        - prod-service
    include:
      - db
      - oauth2
      - common
      - service

logging:
  level:
    com:
      user: debug
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace