spring:
  config:
    activate:
      on-profile: local-service

service:
  j-post-service: http://localhost:8082

---
spring:
  config:
    activate:
      on-profile: prod-service

service:
  j-post-service: ${POST_SERVER}

