spring:
  config:
    activate:
      on-profile: local-service

service:
  j-post-service: http://localhost:8081


---
spring:
  config:
    activate:
      on-profile: prod-service

service:
  j-post-service: http://j-post-service:8080

