spring:
  config:
    activate:
      on-profile: local-oauth2
  jpa:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: ${AUTHORIZATION_GRANT_TYPE}

---

spring:
  config:
    activate:
      on-profile: prod-oauth2
  jpa:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: ${AUTHORIZATION_GRANT_TYPE}


