spring:
  config:
    activate:
      on-profile: local-oauth2
  jpa:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: wuAWZWv8noa7LcgEUPRd
            client-secret: tSBe0L8Ihj
            authorization-grant-type: authorization_code
            client-name: j-project
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # login/oauth2/code는 변경하지 않으면 고정
            scope: profile,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
---

spring:
  config:
    activate:
      on-profile: prod-oauth2
  jpa:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: wuAWZWv8noa7LcgEUPRd
            client-secret: tSBe0L8Ihj
            authorization-grant-type: authorization_code
            client-name: j-project
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # login/oauth2/code는 변경하지 않으면 고정
            scope: profile,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

