spring:
  config:
    activate:
      on-profile: local-gateway

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
      routes:
        - id: user-server
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/user/?(?<segment>.*), /$\{segment}
        - id: post-server
          uri: http://localhost:8082
          predicates:
            - Path=/post/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/post/?(?<segment>.*), /$\{segment}


---
spring:
  config:
    activate:
      on-profile: prod-gateway

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://144.24.80.74:8761/eureka

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://144.24.80.74:80"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
      routes:
        - id: user-server
          uri: http://144.24.80.74:8081
          predicates:
            - Path=/user/**
          filters:
            - Authentication
            - RewritePath=/user/?(?<segment>.*), /$\{segment}
        - id: post-server
          uri: http://144.24.80.74:8082
          predicates:
            - Path=/post/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/post/?(?<segment>.*), /$\{segment}

