server:
  port: 8080

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  profiles:
    active:
      - local
    group:
      local:
        - local-common
        - local-service
        - local-gateway
        - local-authorization
      dev:
        - dev-common
        - dev-service
        - dev-gateway
        - dev-authorization
      prod:
        - prod-common
        - prod-service
        - prod-gateway
        - prod-authorization
    include:
      - common
      - service
      - gateway
      - authorization

  main:
    web-application-type: reactive

logging:
  level:
    com.gateway: debug
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE



