spring:
  config:
    activate:
      on-profile: local-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
      routes:
        - id: user-server
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/user/?(?<segment>.*), /$\{segment}
        - id: post-server
          uri: http://localhost:8082
          predicates:
            - Path=/post/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/post/?(?<segment>.*), /$\{segment}

#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka


---
spring:
  config:
    activate:
      on-profile: prod-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://144.24.80.74"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
      routes:
        - id: user-server
          uri: http://144.24.80.74:8081
          predicates:
            - Path=/user/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/user/?(?<segment>.*), /$\{segment}
        - id: post-server
          uri: http://144.24.80.74:8082
          predicates:
            - Path=/post/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/post/?(?<segment>.*), /$\{segment}

#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka

