spring:
  config:
    activate:
      on-profile: local-common
server:
  shutdown: immediate

jwt:
  secret-key: jmg_project_application_secret_key  #256bit 넘어야 한다
  token-decrypt-key: j-project--token
  expired-time: 600 #600분
  expired-refresh-time: 4320 #3일
---

spring:
  config:
    activate:
      on-profile: dev-common
server:
  shutdown: immediate

jwt:
  secret-key: jmg_project_application_secret_key  #256bit 넘어야 한다
  token-decrypt-key: j-project--token
  expired-time: 600 #600분
  expired-refresh-time: 4320 #3일

---

spring:
  config:
    activate:
      on-profile: prod-common
server:
  shutdown: graceful

jwt:
  secret-key: ${SECRET_KEY}
  token-decrypt-key: ${TOKEN_DECRYPT_KEY}
  expired-time: ${EXPIRED_TIME}
  expired-refresh-time: ${EXPIRED_REFRESH_TIME}