apiVersion: v1
kind: Service
metadata:
  name: j-user-service
  namespace: prod
spec:
  selector:
    app: j-user-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 # pod가 실행되고 있는 포트